version: '3.2'

services:
  elastic-controller:
    image: elastic-controller
    build:
      context: elasticController
      dockerfile: Dockerfile
    volumes:
      - /data/elastic-controller
    ports:
      - "8096:8096"
    networks:
      - elktestdriver

networks:
  elktestdriver:
    driver: bridge
